"""
Star-decoder and U†EU computation for the [[5,1,3]] perfect quantum code.

This script implements:
1. Construction of the ∗-decoder U as a 32×32 unitary: C^32 -> C^2 ⊗ C^16
2. Abstract EC model (perfect syndrome projection + deterministic Pauli correction)
3. Encoded wait gadget with independent depolarizing noise
4. U†EU computation for the full exRec (FTEC - wait - FTEC)
5. Extraction of syndrome-conditioned logical error channels
6. Verification against case-by-case Pauli error analysis

Reference: Gottesman, "Surviving as a Quantum Computer in a Classical World" (2024),
           §14.4.2-14.4.3 (∗-decoder, Eq. 14.27), §10.2.4 (FTEC definitions),
           Table 3.2 (five-qubit code generators), Table 3.4 (logical Paulis).
"""

import numpy as np
from itertools import product as iterproduct
from functools import reduce

# ============================================================
# 1. PAULI INFRASTRUCTURE
# ============================================================

I2 = np.eye(2, dtype=complex)
X = np.array([[0, 1], [1, 0]], dtype=complex)
Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z = np.array([[1, 0], [0, -1]], dtype=complex)

PAULIS_1Q = {'I': I2, 'X': X, 'Y': Y, 'Z': Z}


def kron_list(ops):
    """Tensor product of a list of matrices."""
    return reduce(np.kron, ops)


def pauli_from_string(s):
    """Build n-qubit Pauli from string like 'XZZXI'."""
    return kron_list([PAULIS_1Q[c] for c in s])


# ============================================================
# 2. [[5,1,3]] CODE DEFINITION
# ============================================================

# Stabilizer generators (Gottesman Table 3.2)
STAB_STRINGS = ['XZZXI', 'IXZZX', 'XIXZZ', 'ZXIXZ']
STAB_GENS = [pauli_from_string(s) for s in STAB_STRINGS]

# Logical Paulis (Gottesman Table 3.4)
XBAR_STRING = 'XXXXX'
ZBAR_STRING = 'ZZZZZ'
X_BAR = pauli_from_string(XBAR_STRING)
Z_BAR = pauli_from_string(ZBAR_STRING)

N = 5  # physical qubits
DIM = 2 ** N  # = 32


# ============================================================
# 3. CODESPACE PROJECTOR AND LOGICAL BASIS
# ============================================================

def build_codespace_projector(generators):
    """
    Build Π = (1/2^r) * Σ_{M ∈ S} M
    where S is the full stabilizer group generated by the generators.
    Equivalently: Π = Π_i (I + g_i)/2
    """
    Pi = np.eye(DIM, dtype=complex)
    for g in generators:
        Pi = Pi @ (np.eye(DIM, dtype=complex) + g) / 2.0
    return Pi


def find_codespace_basis(Pi):
    """
    Find orthonormal basis {|0̄⟩, |1̄⟩} for the codespace.
    We diagonalize Π and pick the two eigenvectors with eigenvalue 1.
    Then choose the basis so that Z̄|0̄⟩ = |0̄⟩ and Z̄|1̄⟩ = -|1̄⟩.
    """
    evals, evecs = np.linalg.eigh(Pi)
    # Pick eigenvectors with eigenvalue ≈ 1
    codespace_idx = np.where(np.abs(evals - 1.0) < 1e-10)[0]
    assert len(codespace_idx) == 2, f"Expected 2-dim codespace, got {len(codespace_idx)}"

    # Raw basis vectors
    v0 = evecs[:, codespace_idx[0]]
    v1 = evecs[:, codespace_idx[1]]

    # Diagonalize Z̄ within the codespace to get |0̄⟩, |1̄⟩
    Z_block = np.array([
        [v0.conj() @ Z_BAR @ v0, v0.conj() @ Z_BAR @ v1],
        [v1.conj() @ Z_BAR @ v0, v1.conj() @ Z_BAR @ v1]
    ])
    z_evals, z_evecs = np.linalg.eigh(Z_block)

    # Sort so |0̄⟩ has Z̄ eigenvalue +1, |1̄⟩ has -1
    idx_sort = np.argsort(-z_evals.real)  # +1 first
    z_evecs = z_evecs[:, idx_sort]

    cbar0 = v0 * z_evecs[0, 0] + v1 * z_evecs[1, 0]
    cbar1 = v0 * z_evecs[0, 1] + v1 * z_evecs[1, 1]

    # Normalize
    cbar0 /= np.linalg.norm(cbar0)
    cbar1 /= np.linalg.norm(cbar1)

    return cbar0, cbar1


# ============================================================
# 4. SYNDROME COMPUTATION AND REPRESENTATIVE MAP
# ============================================================

def syndrome_of(pauli_op, generators):
    """
    Compute the 4-bit syndrome of a Pauli operator.
    Syndrome bit i = 0 if pauli_op commutes with generators[i], else 1.
    Returns an integer 0..15.
    """
    bits = []
    for g in generators:
        # Check commutation: gP = Pg (commutes) or gP = -Pg (anticommutes)
        comm = g @ pauli_op - pauli_op @ g
        if np.allclose(comm, 0):
            bits.append(0)
        else:
            bits.append(1)
    return sum(b << (3 - i) for i, b in enumerate(bits))


def build_syndrome_representatives(generators):
    """
    Build a map: syndrome (int) -> representative Pauli (32×32 matrix).

    For the [[5,1,3]] perfect code, the 15 single-qubit errors
    {X_i, Y_i, Z_i : i=1..5} give all 15 nontrivial syndromes,
    and I gives syndrome 0. This exhausts all 16 syndromes.
    """
    syn_rep = {}
    syn_rep_labels = {}

    # Syndrome 0 -> Identity
    syn_rep[0] = np.eye(DIM, dtype=complex)
    syn_rep_labels[0] = 'I'

    for qubit in range(N):
        for name in ['X', 'Y', 'Z']:
            ops = [I2] * N
            ops[qubit] = PAULIS_1Q[name]
            E = kron_list(ops)
            s = syndrome_of(E, generators)
            if s not in syn_rep:
                syn_rep[s] = E
                syn_rep_labels[s] = f'{name}{qubit + 1}'

    assert len(syn_rep) == 16, f"Expected 16 syndrome reps, got {len(syn_rep)}"
    return syn_rep, syn_rep_labels


# ============================================================
# 5. STAR-DECODER CONSTRUCTION
# ============================================================

def build_star_decoder(cbar0, cbar1, syn_rep):
    """
    Build the ∗-decoder U as a 32×32 unitary.

    U : physical Hilbert space C^32 -> C^2 (logical) ⊗ C^16 (syndrome)

    Convention: basis of the output space is |ψ⟩|s⟩ where
      ψ ∈ {0, 1} (logical qubit)
      s ∈ {0, 1, ..., 15} (syndrome)

    Column ordering of U†: column index = 2*s + ψ
    (syndrome runs slow, logical runs fast)

    U† |ψ⟩|s⟩ = E_s |ψ̄⟩

    Ref: Gottesman §14.4.2, Eq. (14.19)
    """
    U_dag = np.zeros((DIM, DIM), dtype=complex)

    for s in range(16):
        E_s = syn_rep[s]
        U_dag[:, 2 * s + 0] = E_s @ cbar0  # |0⟩|s⟩ -> E_s|0̄⟩
        U_dag[:, 2 * s + 1] = E_s @ cbar1  # |1⟩|s⟩ -> E_s|1̄⟩

    # Verify unitarity
    check = U_dag.conj().T @ U_dag
    assert np.allclose(check, np.eye(DIM)), "U† is not unitary!"

    U = U_dag.conj().T  # U = (U†)†
    return U, U_dag


# ============================================================
# 6. ABSTRACT EC MODEL
# ============================================================

def abstract_EC(state_vec):
    """
    Abstract (ideal) error correction:
    1. Project onto syndrome eigenspace (= measure syndrome perfectly)
    2. Apply the correction Pauli for that syndrome
    3. Result: state is projected back into the codespace with syndrome 0

    This implements perfect EC as a CP map on state vectors.
    For a density matrix, you'd sum over syndromes; here we do it
    for a single state vector and return the corrected state + measured syndrome.

    NOTE: In the abstract model, this ALWAYS resets syndrome to 0,
    which is why it kills syndrome memory and makes logical errors
    syndrome-independent. (Gottesman §14.4.2)
    """
    # Build syndrome projectors
    results = []
    for s in range(16):
        # Projector onto syndrome-s subspace
        P_s = np.zeros((DIM, DIM), dtype=complex)
        for bits in iterproduct([0, 1], repeat=4):
            sign = np.eye(DIM, dtype=complex)
            for i, b in enumerate(bits):
                if b == 0:
                    sign = sign @ (np.eye(DIM, dtype=complex) + STAB_GENS[i]) / 2
                else:
                    sign = sign @ (np.eye(DIM, dtype=complex) - STAB_GENS[i]) / 2
            if tuple(bits) == tuple((s >> (3 - i)) & 1 for i in range(4)):
                P_s += sign

        projected = P_s @ state_vec
        prob = np.real(projected.conj() @ projected)
        if prob > 1e-15:
            results.append((s, prob, projected))

    return results


def build_syndrome_projectors():
    """Build all 16 syndrome projectors for the [[5,1,3]] code."""
    projectors = {}
    for s in range(16):
        # Syndrome s has bit pattern: bit i = (s >> (3-i)) & 1
        P_s = np.eye(DIM, dtype=complex)
        for i in range(4):
            bit = (s >> (3 - i)) & 1
            if bit == 0:
                P_s = P_s @ (np.eye(DIM, dtype=complex) + STAB_GENS[i]) / 2
            else:
                P_s = P_s @ (np.eye(DIM, dtype=complex) - STAB_GENS[i]) / 2
        projectors[s] = P_s
    return projectors


def abstract_EC_operator(syn_projectors, syn_rep):
    """
    Build the abstract EC as a single 32×32 operator (for no-fault case):

    EC = Σ_s  E_s†  P_s

    This projects onto the syndrome-s subspace, then applies correction E_s†.
    The result is always in the codespace (syndrome 0).

    This is a sum of orthogonal terms, so it's a valid (unnormalized) operator
    on state vectors. On density matrices: EC(ρ) = Σ_s E_s† P_s ρ P_s E_s
    """
    EC = np.zeros((DIM, DIM), dtype=complex)
    for s in range(16):
        E_s = syn_rep[s]
        P_s = syn_projectors[s]
        EC += E_s.conj().T @ P_s
    return EC


# ============================================================
# 7. DEPOLARIZING NOISE
# ============================================================

def depolarizing_kraus(p):
    """
    Independent single-qubit depolarizing channel on all 5 qubits.

    Single-qubit channel: ρ -> (1-p)ρ + (p/3)(XρX + YρY + ZρZ)

    Kraus operators for single qubit:
      sqrt(1-p) I,  sqrt(p/3) X,  sqrt(p/3) Y,  sqrt(p/3) Z

    For 5 qubits (independent): tensor product of single-qubit Kraus ops.
    Total: 4^5 = 1024 Kraus operators.
    """
    coeffs_1q = {
        'I': np.sqrt(1 - p),
        'X': np.sqrt(p / 3),
        'Y': np.sqrt(p / 3),
        'Z': np.sqrt(p / 3),
    }

    kraus_ops = []
    labels = []
    pauli_names = ['I', 'X', 'Y', 'Z']

    for combo in iterproduct(pauli_names, repeat=N):
        coeff = 1.0
        ops = []
        for c in combo:
            coeff *= coeffs_1q[c]
            ops.append(PAULIS_1Q[c])
        K = coeff * kron_list(ops)
        kraus_ops.append(K)
        labels.append(''.join(combo))

    return kraus_ops, labels


# ============================================================
# 8. FULL exRec ACTION: FTEC - WAIT - FTEC (abstract EC)
# ============================================================

def build_exrec_action_abstract(p, syn_projectors, syn_rep):
    """
    Build the exRec action E as a quantum channel (list of Kraus operators)
    for the circuit:  FTEC_ideal - (depolarizing wait) - FTEC_ideal

    In the ABSTRACT EC model:
    - FTEC is faultless (no noise in EC itself)
    - EC perfectly measures syndrome and applies correction
    - Noise only occurs during the wait step (depolarizing on all 5 qubits)

    The exRec action on a density matrix ρ is:
      E(ρ) = EC · N(ρ) · EC†
    where N is the depolarizing channel during the wait.

    More precisely, the Kraus operators of the full exRec are:
      {EC_trailing · K_noise · EC_leading}  for each noise Kraus K_noise

    But since EC_leading just projects to codespace (no fault),
    and EC_trailing projects back, the effective Kraus ops are:
      {EC · K · EC}  where EC = Σ_s E_s† P_s

    IMPORTANT: In this abstract model, each EC resets syndrome to 0.
    Therefore the logical errors will be syndrome-INDEPENDENT.
    To see syndrome-dependent (non-Markovian) structure, you need
    the realistic fault model.
    """
    EC = abstract_EC_operator(syn_projectors, syn_rep)
    noise_kraus, noise_labels = depolarizing_kraus(p)

    exrec_kraus = []
    exrec_labels = []
    for K, label in zip(noise_kraus, noise_labels):
        # Full exRec Kraus: EC_trailing · K · EC_leading
        kraus = EC @ K @ EC
        exrec_kraus.append(kraus)
        exrec_labels.append(label)

    return exrec_kraus, exrec_labels


# ============================================================
# 9. U†EU COMPUTATION
# ============================================================

def compute_logical_channel(U, U_dag, exrec_kraus):
    """
    Compute U†EU for each Kraus operator of the exRec.

    For each Kraus operator K of the exRec:
      K_logical = U · K · U†

    This gives a 32×32 matrix in the (logical, syndrome) basis.
    The 2×2 block at row-block s_out, column-block s_in gives
    the logical transformation conditioned on:
      - incoming syndrome s_in
      - outgoing syndrome s_out

    Ref: Gottesman §14.4.3, Eq. (14.27)
    """
    logical_kraus = []
    for K in exrec_kraus:
        K_logical = U @ K @ U_dag
        logical_kraus.append(K_logical)
    return logical_kraus


def extract_logical_channel_block(logical_kraus, s_in, s_out):
    """
    Extract the 2×2 logical channel block for given syndrome transition.

    Returns the channel as a list of 2×2 Kraus operators.
    The logical channel is: ρ_L -> Σ_k  M_k ρ_L M_k†
    where M_k is the 2×2 block of the k-th logical Kraus operator.
    """
    blocks = []
    for K_L in logical_kraus:
        block = K_L[2 * s_out:2 * s_out + 2, 2 * s_in:2 * s_in + 2]
        blocks.append(block)
    return blocks


def logical_pauli_channel_coefficients(logical_kraus, s_in, s_out):
    """
    Decompose the syndrome-conditioned logical channel into Pauli coefficients.

    For a Pauli channel on a single qubit:
      ρ -> p_I ρ + p_X XρX + p_Y YρY + p_Z ZρZ

    The coefficients are found by:
      p_P = Σ_k |Tr(P · M_k)|² / 4   (for each Pauli P)

    Actually, more carefully: the Choi matrix of the channel determines everything.
    For a single-qubit channel with Kraus ops {M_k}:
      χ_{PQ} = Σ_k Tr(P M_k) Tr(Q M_k)* / 4

    For a Pauli channel, χ is diagonal in the Pauli basis.
    """
    blocks = extract_logical_channel_block(logical_kraus, s_in, s_out)

    paulis = [I2, X, Y, Z]
    pauli_names = ['I', 'X', 'Y', 'Z']

    # Process matrix χ_{PQ} = Σ_k Tr(P · M_k) · Tr(Q · M_k)* / 4
    chi = np.zeros((4, 4), dtype=complex)
    for M in blocks:
        coeffs = np.array([np.trace(P @ M) for P in paulis])  # length 4
        chi += np.outer(coeffs, coeffs.conj()) / 4.0

    # For a Pauli channel, the diagonal gives the Pauli error probabilities
    p_coeffs = {pauli_names[i]: np.real(chi[i, i]) for i in range(4)}

    return p_coeffs, chi


# ============================================================
# 10. MAIN: RUN EVERYTHING
# ============================================================

def main():
    print("=" * 70)
    print("  ∗-DECODER AND U†EU FOR THE [[5,1,3]] PERFECT CODE")
    print("  Abstract EC model with depolarizing noise")
    print("=" * 70)

    # --- Build code infrastructure ---
    print("\n--- Building codespace projector ---")
    Pi = build_codespace_projector(STAB_GENS)
    print(f"  Rank of Π: {int(np.round(np.trace(Pi).real))} (expect 2)")

    print("\n--- Finding codespace basis ---")
    cbar0, cbar1 = find_codespace_basis(Pi)

    # Verify logical Paulis
    print(f"  ⟨0̄|Z̄|0̄⟩ = {cbar0.conj() @ Z_BAR @ cbar0:.6f} (expect +1)")
    print(f"  ⟨1̄|Z̄|1̄⟩ = {cbar1.conj() @ Z_BAR @ cbar1:.6f} (expect -1)")
    print(f"  ⟨0̄|X̄|1̄⟩ = {cbar0.conj() @ X_BAR @ cbar1:.6f} (expect +1)")
    print(f"  ⟨0̄|1̄⟩   = {cbar0.conj() @ cbar1:.6f} (expect 0)")

    print("\n--- Building syndrome representatives ---")
    syn_rep, syn_labels = build_syndrome_representatives(STAB_GENS)
    print("  Syndrome -> Representative:")
    for s in range(16):
        print(f"    s={s:04b} ({s:2d}) -> {syn_labels[s]}")

    print("\n--- Constructing ∗-decoder U ---")
    U, U_dag = build_star_decoder(cbar0, cbar1, syn_rep)
    print(f"  U is {U.shape[0]}×{U.shape[1]}")
    print(f"  UU† = I: {np.allclose(U @ U_dag, np.eye(DIM))}")
    print(f"  U†U = I: {np.allclose(U_dag @ U, np.eye(DIM))}")

    # Verify ∗-decoder action on a few states
    print("\n--- Verifying ∗-decoder ---")
    # U applied to |0̄⟩ (syndrome 0) should give |0⟩|0000⟩
    logical_state = U @ cbar0
    print(f"  U|0̄⟩: logical part = |{np.argmax(np.abs(logical_state[:2]))}⟩, "
          f"syndrome = {np.argmax(np.sum(np.abs(logical_state.reshape(16, 2)) ** 2, axis=1))}")

    # U applied to X_1|0̄⟩ should give |?⟩|syndrome of X_1⟩
    X1 = kron_list([X, I2, I2, I2, I2])
    test_state = U @ (X1 @ cbar0)
    syn_probs = np.sum(np.abs(test_state.reshape(16, 2)) ** 2, axis=1)
    detected_syn = np.argmax(syn_probs)
    expected_syn = syndrome_of(X1, STAB_GENS)
    print(f"  U(X₁|0̄⟩): detected syndrome = {detected_syn:04b}, "
          f"expected = {expected_syn:04b}, match = {detected_syn == expected_syn}")

    # --- Build abstract EC ---
    print("\n--- Building abstract EC operator ---")
    syn_projectors = build_syndrome_projectors()
    EC = abstract_EC_operator(syn_projectors, syn_rep)

    # Verify EC maps codespace to codespace
    test = EC @ cbar0
    overlap_0 = np.abs(test.conj() @ cbar0) ** 2
    print(f"  EC|0̄⟩ overlap with |0̄⟩: {overlap_0:.6f} (expect 1)")

    # Verify EC corrects single errors
    test_corrected = EC @ (X1 @ cbar0)
    overlap_corrected = np.abs(test_corrected.conj() @ cbar0) ** 2
    print(f"  EC(X₁|0̄⟩) overlap with |0̄⟩: {overlap_corrected:.6f} (expect 1)")

    # --- Compute logical channel for several p values ---
    print("\n" + "=" * 70)
    print("  LOGICAL ERROR CHANNEL (Abstract EC, encoded wait)")
    print("=" * 70)

    p_values = [0.001, 0.01, 0.05, 0.1]

    for p in p_values:
        print(f"\n--- p = {p} ---")
        exrec_kraus, _ = build_exrec_action_abstract(p, syn_projectors, syn_rep)
        logical_kraus = compute_logical_channel(U, U_dag, exrec_kraus)

        # For abstract EC, all syndromes reset to 0, so only s_in=0, s_out=0 matters
        p_coeffs, chi = logical_pauli_channel_coefficients(logical_kraus, s_in=0, s_out=0)

        print(f"  Logical Pauli channel (s_in=0 -> s_out=0):")
        print(f"    p_I = {p_coeffs['I']:.10f}")
        print(f"    p_X = {p_coeffs['X']:.10f}")
        print(f"    p_Y = {p_coeffs['Y']:.10f}")
        print(f"    p_Z = {p_coeffs['Z']:.10f}")
        print(f"    p_X + p_Y + p_Z = {p_coeffs['X'] + p_coeffs['Y'] + p_coeffs['Z']:.10f}")

        # Compare with known exact result:
        # p̄_X = p̄_Y = p̄_Z = (10/3)p² − (200/27)p³ + (160/27)p⁴ − (128/81)p⁵
        p_bar_exact = (10 / 3) * p ** 2 - (200 / 27) * p ** 3 + (160 / 27) * p ** 4 - (128 / 81) * p ** 5
        print(f"    Exact (10/3)p² - ... = {p_bar_exact:.10f}")
        print(f"    Match p_X ≈ exact: {np.isclose(p_coeffs['X'], p_bar_exact, rtol=1e-6)}")

        # Verify that chi is diagonal (it's a Pauli channel)
        off_diag = np.sum(np.abs(chi) ** 2) - np.sum(np.abs(np.diag(chi)) ** 2)
        print(f"    χ off-diagonal norm²: {off_diag:.2e} (expect ~0 for Pauli channel)")

        # Check all syndrome blocks are zero except (0,0)
        nonzero_blocks = []
        for s_in_test in range(16):
            for s_out_test in range(16):
                blocks = extract_logical_channel_block(logical_kraus, s_in_test, s_out_test)
                norm = sum(np.linalg.norm(b) ** 2 for b in blocks)
                if norm > 1e-15:
                    nonzero_blocks.append((s_in_test, s_out_test, norm))

        print(f"    Non-zero syndrome blocks: {len(nonzero_blocks)}")
        for s_in_t, s_out_t, norm in nonzero_blocks:
            print(f"      ({s_in_t:04b} -> {s_out_t:04b}): ||block||² = {norm:.6f}")

    # --- Demonstrate syndrome dependence (what would happen WITHOUT
    #     abstract EC resetting syndrome) ---
    print("\n" + "=" * 70)
    print("  SYNDROME-DEPENDENT ANALYSIS")
    print("  (Showing why abstract EC kills non-Markovianity)")
    print("=" * 70)

    p = 0.05
    print(f"\n  Using p = {p}")

    # Build exRec with only ONE trailing EC (to see what happens mid-circuit)
    # Here: just noise (no leading EC) followed by trailing EC
    # This shows how syndrome-conditioned errors look BEFORE the final EC resets
    noise_kraus, noise_labels = depolarizing_kraus(p)

    # Compute U†KU for raw noise (no EC at all)
    print("\n  Raw noise channel (NO EC), syndrome-conditioned blocks:")
    raw_logical_kraus = [U @ K @ U_dag for K in noise_kraus]

    for s_in_test in [0, 1, 5]:
        p_coeffs_raw, _ = logical_pauli_channel_coefficients(
            raw_logical_kraus, s_in=s_in_test, s_out=s_in_test)
        total_err = p_coeffs_raw['X'] + p_coeffs_raw['Y'] + p_coeffs_raw['Z']
        print(f"    s_in={s_in_test:04b}: p_I={p_coeffs_raw['I']:.6f}, "
              f"p_err={total_err:.6f}")

    # --- Full U†EU matrix visualization for one p ---
    print("\n" + "=" * 70)
    print("  FULL U†EU MATRIX STRUCTURE (p = 0.05, abstract EC)")
    print("=" * 70)

    p = 0.05
    exrec_kraus, _ = build_exrec_action_abstract(p, syn_projectors, syn_rep)
    logical_kraus = compute_logical_channel(U, U_dag, exrec_kraus)

    # Build the logical channel's Choi matrix (or just the Pauli transfer matrix)
    # Show the 16×16 block structure
    print("\n  Frobenius norm of each 2×2 block Σ_k ||M_k(s_out,s_in)||²:")
    print("  (rows = s_out, cols = s_in)")
    print()
    header = "       " + "  ".join(f"{s:4d}" for s in range(16))
    print(header)
    print("       " + "-" * (6 * 16))
    for s_out in range(16):
        row_vals = []
        for s_in in range(16):
            blocks = extract_logical_channel_block(logical_kraus, s_in, s_out)
            norm = sum(np.linalg.norm(b) ** 2 for b in blocks)
            row_vals.append(norm)
        row_str = f"  {s_out:4d} |" + "  ".join(f"{v:4.2f}" for v in row_vals)
        print(row_str)

    print("\n" + "=" * 70)
    print("  SUMMARY")
    print("=" * 70)
    print("""
  KEY FINDINGS:

  1. In the abstract EC model, FTEC always resets syndrome to 0000.
     Therefore, U†EU has non-zero blocks ONLY at (s_in=0, s_out=0).
     This means logical errors are syndrome-INDEPENDENT -> Markovian.

  2. The logical error channel is a Pauli channel with:
     p̄_X = p̄_Y = p̄_Z = (10/3)p² - (200/27)p³ + (160/27)p⁴ - (128/81)p⁵

  3. To see syndrome-dependent (non-Markovian) logical errors, you need
     the REALISTIC fault model where syndrome measurement itself has faults.
     Then EC may apply the WRONG correction, leaving residual errors
     with nontrivial syndrome that persist to the next round.

  REFERENCES:
  - Gottesman QECCbook-2024, §14.4.2 (∗-decoder), §14.4.3 (U†EU, Eq. 14.27)
  - Gottesman QECCbook-2024, Table 3.2 (five-qubit code generators)
  - Gottesman QECCbook-2024, Table 3.4 (logical Paulis: X̄=XXXXX, Z̄=ZZZZZ)
  - Gottesman QECCbook-2024, §10.2.4 (FTEC properties: ECRP, ECCP)
    """)


if __name__ == '__main__':
    main()